### ISSUE TITLE
Facet selection generates invalid query expression

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/simple-search-js#2]
I've imported a csv file into the Simple-Search-Service. One input field was detected as "number". I've changed the data type to "string" and selected this field as a facet for index creation.
Using simple-search-js if one selects one of the values (e.g. `6`) from the facet list, a query like the following is generated: `field:6` and no results are returned.

**Comment by vabarbosa** [comment]
resolved by pull request #3
